language: python
cache: pip
os:
  - linux
python:
  - '3.6'
install:
  - pip install -r requirements.txt
script:
  # py.test -s
  python -m pytest
deploy:
  provider: pypi
  user: alejoe91
  on:
    tags: true
  password:
    secure: Ya7Z6AouMhTiBA7G8sUNncA92h+j+JTW4a8AwyDklFB/0poxrhUZwpfMj80yaLfEGspTFaUCvc5oBQB3bLbrHmYAFP3TQKm2X8tQSR5XZXew1uvtGBVMebW4DHSFeQLEVyHjY6q8tzA0jSbHetVlc+Vfv3xtAeD4w7Ff2x4HoWQJUKMkdVvROi/OIjLeTqiMc7LOGfDtT0AJUFp86u1auv8Mriw9L06dKI9E9SFd1t85sOv/RosTtQD/f8o0kHZbkkkpQOSLsh5xQZ472pGk/zfvAk1BEB7hr1eaWNeJqdk/NQL1ONr5nvs5O0SzURz/PH8lAMBdV1tr5NzBWXy7dTtHPW7WXvJlvZR/s39XZFRnSWXJlhvZRoGrY54tzpYjnH5+dkzdZYcTcCIgpmNPGGZ8cckq5E4pQTAduhIwfTJ5v8EMBMFqXpr9+T+ynk/MXkDX2x1VSGetTpR2IR+mAx49xi7gC+4YmbJk7Y0lATNpoCSAcf0pSrYHtPsrUhU/2sd4PGFxkrqTTluf1LJb/g+IFSF8EnaQFCoBcxmJUVDyM+LReAhTjaENFKB9r7H75YZE9h0xcC0N/dGEeZGE3DVmfkfJIDGtdDezXuWlrWZQT6ICvItasA8RZn1v+MtwuenQI8050emwvaNvStypkQEpcYuTkV59FzT828pK5cE=
