language: python
cache: pip
os:
- linux
python:
- '3.6'
install:
- pip install matplotlib==3.2.2
- pip install -r requirements.txt
- pip install -r requirements_rtd.txt
- pip install sphinx pillow sphinx-gallery
- pip install .
script:
- python -m pytest --ignore=doc/
- cd doc
- make html
deploy:
  provider: pypi
  user: alejoe91
  on:
    tags: true
  password:
    secure: xswCobHMF5bPstn5Yc1I5n8XenWEPOXqqL9g9IbiiFmHu+r/eFHg+57wg7ih2tT4UsDBALMhMx+wjr1THEzljf8MpWEAd+hjN1qpWWSj5TpaDFlFB+uxY1vRiO2DNToi4XyI0/F8cUlmk6KrBG8XcyTB5SbySU74JOdZ94KMkKiVH5Lz19gvReACqF1kYCsgkVDyVN5pAoOXDDb2Mb9Om/CsWOnIEpdA/onXXjHn/hKse6rhY81yclMNHGgvZPVCLfGxa1nwGKuaI4dxczZ9SxhZiV7BLmi/roQk9kSe0p3/B0qAly9yJvffmr1JVxTLtfvya5NH5lwJs110cbB+RLA58yRYtBmFM4VX+QwVfyzqAqtUfKzsrHPxdWdVsIxiy5Cm2Dn1c1dV/KYBbbex6e3FNV1H7NYUwi1tv8+DYbFMhFCWwfjqH7PmO5SuHCM0Y10DgmYeLfS+BbBPALwcoJtugjYXXs8myHmOwL2DVFcMSFORJ9IsUCA/z2pnexMYSNgJ2T8IdwoxxDkg81zXck+bcjYWQNfR4AFs1bm7G7KdjwDUJ+C0rSgugErX4RT6KvrbvPz9Q6NMTUVXdr314Mwvt4BQB/LQ2Mi3KXhyEaQNbkrPfGQ6R5ndK5GOdNR97ZcOnyXxzdK55LsjvqU/3G5/LV747X8olq9iObi7qOk=
