name: si_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip>=21.0
  # numpy 1.21 break numba which break tridesclous
  - numpy<1.22
  # joblib 1.2 is breaking hdbscan
  - joblib=1.1
  - tqdm
  - matplotlib
  - h5py
  - pandas
  - scikit-learn
  - networkx
  - pybind11
  - loky
  - hdbscan
  - numba
  - jupyter
  - pyqt=5
  - pyqtgraph
  - ipywidgets
  - ipympl
  - pip:
    - ephyviewer
    - neo>=0.11
    - elephant>=0.10.0
    - probeinterface>=0.2.11
    - MEArec>=1.8
    - spikeinterface[full, widgets]
    - spikeinterface-gui
    - tridesclous>=1.6.6.1
    # - phy==2.0b5
