name: si_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip>=21.0
  # numpy 1.21 break numba which break tridesclous
  - numpy<1.21
  - joblib
  - tqdm
  - matplotlib
  - h5py
  - pandas
  - scikit-learn
  - networkx
  - pybind11
  - loky
  - hdbscan
  - numba
  - jupyter
  - mpi4py
  - compilers
  - pip:
    - PyQt5
    - ephyviewer
    - neo>=0.10.0
    - elephant>=0.10.0
    - probeinterface
    - MEArec>=1.7.1
    - spikeinterface[full]
    - spikeinterface-gui
    - tridesclous>=1.6.3
    - spyking-circus>=1.0.9
    
#    - herdingspikes
#    - isosplit5
#    - mountainsort4>=1.0.0
