name: si_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip>=21.0
  # numpy 1.21 break numba which break tridesclous
  - numpy<1.22
  - joblib
  - tqdm
  - matplotlib
  - h5py
  - pandas
  - scikit-learn
  - networkx
  - pybind11
  - loky
  - hdbscan
  - numba
  - jupyter
  - mpi4py
  - compilers
  - pip:
    - ephyviewer
    - spikeinterface[full, extractors]
    - spikeinterface-gui
    - phy==2.0b5
