name: Install packages
description: This action installs the package and its dependencies for testing

inputs:
  python-version:
    description: 'Python version to set up'
    required: false
  os:
    description: 'Operating system to set up'
    required: false

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: |
        sudo apt install git
        git config --global user.email "CI@example.com"
        git config --global user.name "CI Almighty"
        python -m venv ${{ github.workspace }}/test_env # Environment used in the caching step
        python -m pip install -U pip  # Official recommended way
        source ${{ github.workspace }}/test_env/bin/activate
        pip install tabulate  # This produces summaries at the end
        pip install -e .[test,extractors,full]
      shell: bash
    - name: Force installation of latest dev from key-packages
      id: version
      run: |
        source ${{ github.workspace }}/test_env/bin/activate
        pip uninstall -y neo  # The -y flag is needed to avoid the user prompt
        pip uninstall -y probeinterface
        pip install git+https://github.com/NeuralEnsemble/python-neo
        pip install git+https://github.com/SpikeInterface/probeinterface
      shell: bash
    - name: git-annex install
      run: |
        wget https://downloads.kitenet.net/git-annex/linux/current/git-annex-standalone-amd64.tar.gz
        tar xvzf git-annex-standalone-amd64.tar.gz
        echo "$(pwd)/git-annex.linux" >> $GITHUB_PATH
      shell: bash
