name: Check changed matlab files

on:
  push:
    branches:
      - master
      - changed-matlab-files

jobs:
  check-matlab-changed:
    name: Check changed files
    runs-on: "ubuntu-latest"
    outputs:
      has_changed_files: ${{ steps.changed-files.outputs.any_changed }}
      changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v23
        with:
          files: |
            **/*.m

  create-issue:
    name: Create Issue
    needs: check-matlab-changed
    if: needs.check-matlab-changed.outputs.has_changed_files == 'true'
    runs-on: "ubuntu-latest"
    permissions:
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Parse files names
        id: parse-files-names
        run: |
          for file in ${{ needs.check-matlab-changed.outputs.changed_files }}; do
            # return (\n) characters: %0A
            file_list+="%0A- \`${file}\`"
          done
          echo ${file_list}
          echo "::set-output name=file_list::${file_list}"
      - name: Create new issue
        uses: imjohnbo/issue-bot@v3
        with:
          title: Matlab file was changed
          body: |-
            This is a reminder issue.

            Please recompile and rebuild image for the matlab-based sorters that uses the following changed files:
            ${{ steps.parse-files-names.outputs.file_list }}
