name: Ruff Linting

on:
  pull_request:
    types: [synchronize, opened, reopened]
    branches:
      - main

concurrency:  # Cancel previous workflows on the same pull request
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  ruff-linting:
    name: Ruff Linting
    strategy:
      fail-fast: false
    steps:
      - uses: astral-sh/ruff-action@v3
