name: Test sorter images in Docker

on: workflow_dispatch


jobs:
  test-images:
    name: Test on (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Python version
        run:
          python --version
      - name: Docker version
        run:
          docker --version
      - name: Install dependencies
        run: |
          python -m pip install -U pip  # Official recommended way
          pip install pytest
          pip install -e .[full]
          pip install docker
      - name: Run test docker containers
        run: |
          pytest -vv --capture=tee-sys -rA src/spikeinterface/sorters/external/tests/test_docker_containers.py
